version: "3"

services:
  mysql_development:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "DB_DEVELOPMENT_DOCKER"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33061:3306"

  mysql_test:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "DB_TEST_DOCKER"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33062:3306"

  node_server:
    image: node:14-alpine
    environment:
      APP_URL: "http://localhost:3000"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    # for debugging and manually running commands inside of the node_server
    # replace the command to: tail -f /dev/null
    # and then run: docker-compose exec node_server sh
    #
    # command: tail -f /dev/null
    command: >
      sh -c
      "(cd app && sh setup-dev-environment)
      & (cd app/services/socket-io && npm install && npm run start)
      & (cd app/services/cli && npm install && npm run dev)"