version: "3"

services:
  mysql_development:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "DB_DEVELOPMENT_DOCKER"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33061:3306"

  mysql_test:
    image: mysql:8
    environment:
      MYSQL_DATABASE: "DB_TEST_DOCKER"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "33062:3306"

  socket_io:
    image: node:16-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./services/socket-io:/app/server
    command: sh -c "cd /app/server && yarn && yarn start"
