import fs from "fs";
import glob from "glob";

import { APPS_PATH, GENERATED_FILES_PATH } from "../constants";

export default class AppStoreApiFileGenerator {
  FILE_NAME = "api.generated.ts";

  generateFile() {
    glob(APPS_PATH + "/**/pages/api/**", (error, files) => {
      if (error) this.generateFileErrorHandling(error);

      const allFilesInCorrectFormat = files
        .filter((file) => this.isFileWithTsJsEnding(file))
        .map((file) => this.formatFilePath(file));

      const filePath = `${GENERATED_FILES_PATH}/${this.FILE_NAME}`;
      const fileContent = this.generateAppImportsFile(allFilesInCorrectFormat);

      fs.writeFile(filePath, fileContent, this.generateFileErrorHandling);
      console.info(`Generated file: ${filePath}`);
    });
  }

  private generateAppImportsFile(files: string[]) {
    let appImportsContent = "";
    files.forEach((file) => {
      const apiPath = this.buildApiPathFromFilePath(file);
      appImportsContent += `  "${apiPath}": import("../../apps/${file}"),\n`;
    });

    return this.fileContent(appImportsContent);
  }

  private isFileWithTsJsEnding(file: string) {
    const hasTsJsEndingRegex = /.*\.ts$|.*\.js$/;
    const hasTsJsEnding = hasTsJsEndingRegex.test(file);
    return hasTsJsEnding;
  }

  private formatFilePath(file: string) {
    // '/app/src/app-store/apps/mini-blog/pages/api/create.ts'
    // becomes
    // 'mini-blog/pages/api/create'
    const relativePath = this.getRelativePathFromFile(file);
    return this.removeFileEnding(relativePath);
  }

  private removeFileEnding(file: string) {
    // 'mini-blog/pages/api/create.ts'
    // becomes
    // 'mini-blog/pages/api/create'
    const withoutFileEnding = file.split(".")[0];
    if (!withoutFileEnding) throw new Error("removeFileEnding failed");
    return withoutFileEnding;
  }

  private getRelativePathFromFile(file: string) {
    // '/app/src/app-store/apps/mini-blog/pages/api/create.ts'
    // becomes
    // 'mini-blog/pages/api/create.ts'
    const relativePath = file.split("app/src/app-store/apps/")[1];
    if (!relativePath) throw new Error("getRelativePathFromFile failed");
    return relativePath;
  }

  private buildApiPathFromFilePath(file: string) {
    // 'mini-blog/pages/api/create'
    // becomes
    // 'mini-blog/create'
    return file.split("/pages/api/").join("/");
  }

  private generateFileErrorHandling = (error: NodeJS.ErrnoException | null) => {
    if (error) console.error(error);
  };

  private fileContent(apiEndpointsContent: string) {
    return `// *********************************************************************
// This file is autogenerated with /cli/app-store-generate-files.ts
// Don't modify this file manually
// *********************************************************************
type ApiEndpoints = { [key: string]: unknown };\n
export const apiEndpoints: ApiEndpoints = {\n${apiEndpointsContent}};\n`;
  }
}
