// *********************************************************************
// This file is autogenerated with /cli/app-store-generate-files.ts
// Don't modify this file manually
// *********************************************************************
type ApiEndpoints = { [key: string]: unknown };

export const apiEndpoints: ApiEndpoints = {
  "ai-chat/chat/create": import("../../apps/ai-chat/pages/api/chat/create"),
  "mini-blog/posts/[id]/delete": import("../../apps/mini-blog/pages/api/posts/[id]/delete"),
  "mini-blog/posts/[id]/show": import("../../apps/mini-blog/pages/api/posts/[id]/show"),
  "mini-blog/posts/[id]/update": import("../../apps/mini-blog/pages/api/posts/[id]/update"),
  "mini-blog/posts/create": import("../../apps/mini-blog/pages/api/posts/create"),
  "mini-blog/posts/list": import("../../apps/mini-blog/pages/api/posts/list"),
  "town-square/messages/[id]/delete": import("../../apps/town-square/pages/api/messages/[id]/delete"),
  "town-square/messages/create": import("../../apps/town-square/pages/api/messages/create"),
  "town-square/messages/list": import("../../apps/town-square/pages/api/messages/list"),
  "town-square/threads/[id]/delete": import("../../apps/town-square/pages/api/threads/[id]/delete"),
  "town-square/threads/[id]/show": import("../../apps/town-square/pages/api/threads/[id]/show"),
  "town-square/threads/create": import("../../apps/town-square/pages/api/threads/create"),
  "town-square/threads/list": import("../../apps/town-square/pages/api/threads/list"),
};
