// *********************************************************************
// This file is autogenerated with /cli/app-store-generate-files.ts
// Don't modify this file manually
// *********************************************************************
import dynamic from "next/dynamic";

type Imports = { [key: string]: React.ElementType };

export const AppImports: Imports = {
  "mini-blog": dynamic(() => import("@app-store/apps/mini-blog/pages/index")),
  "mini-blog/posts/[id]/edit": dynamic(() => import("@app-store/apps/mini-blog/pages/posts/[id]/edit")),
  "mini-blog/posts/[id]": dynamic(() => import("@app-store/apps/mini-blog/pages/posts/[id]/index")),
  "mini-blog/posts/new": dynamic(() => import("@app-store/apps/mini-blog/pages/posts/new")),
  "simba-design-system": dynamic(() => import("@app-store/apps/simba-design-system/pages/index")),
  "subscriptions": dynamic(() => import("@app-store/apps/subscriptions/pages/index")),
  "subscriptions/pages": dynamic(() => import("@app-store/apps/subscriptions/pages/pages/index")),
  "subscriptions/posts": dynamic(() => import("@app-store/apps/subscriptions/pages/posts/index")),
  "subscriptions/posts/new": dynamic(() => import("@app-store/apps/subscriptions/pages/posts/new")),
  "subscriptions/settings": dynamic(() => import("@app-store/apps/subscriptions/pages/settings/index")),
  "subscriptions/stats": dynamic(() => import("@app-store/apps/subscriptions/pages/stats/index")),
  "town-square": dynamic(() => import("@app-store/apps/town-square/pages/index")),
  "town-square/threads/[id]": dynamic(() => import("@app-store/apps/town-square/pages/threads/[id]/index")),
};
