import fs from "fs";
import glob from "glob";
import path from "path";

export default class AppStoreApiFileGenerator {
  APP_STORE_PATH = path.join(__dirname, "..", "app-store");
  APPS_PATH = path.join(this.APP_STORE_PATH, "apps");
  GENERATED_FILES_PATH = path.join(this.APP_STORE_PATH, "config", "generated-files");
  FILE_NAME = "api.generated.ts";

  generateFile() {
    glob(this.APPS_PATH + "/**/pages/api/**", (error, files) => {
      if (error) this.generateFileErrorHandling(error);

      const allFilesInCorrectFormat = files
        .filter((file) => this.isFileWithTsJsEnding(file))
        .map((file) => this.formatFilePath(file));

      const filePath = `${this.GENERATED_FILES_PATH}/${this.FILE_NAME}`;
      const fileContent = this.generateAppImportsFile(allFilesInCorrectFormat);

      fs.writeFile(filePath, fileContent, this.generateFileErrorHandling);
      console.info(`Generated file: ${filePath}`);
    });
  }

  private generateAppImportsFile(files: string[]) {
    let appImportsContent = "";
    files.forEach((file) => {
      const apiPath = this.buildApiPathFromFilePath(file);
      appImportsContent += `  "${apiPath}": import("../../apps/${file}"),\n`;
    });

    return this.fileContent(appImportsContent);
  }

  private isFileWithTsJsEnding(file: string) {
    const hasTsJsEndingRegex = /.*\.ts$|.*\.js$/;
    const hasTsJsEnding = hasTsJsEndingRegex.test(file);
    return hasTsJsEnding;
  }

  private formatFilePath(file: string) {
    // '/Users/daniel/dev/superapp/app-store/apps/mini-blog/pages/api/create.ts'
    // becomes
    // 'mini-blog/pages/api/create'
    const relativePath = this.getRelativePathFromFile(file);
    return this.removeFileEnding(relativePath);
  }

  private removeFileEnding(file: string) {
    // 'mini-blog/pages/api/create.ts'
    // becomes
    // 'mini-blog/pages/api/create'
    return file.split(".")[0];
  }

  private getRelativePathFromFile(file: string) {
    // '/Users/daniel/dev/superapp/app-store/apps/mini-blog/pages/api/create.ts'
    // becomes
    // 'mini-blog/pages/api/create.ts'
    return file.split("superapp/app-store/apps/")[1];
  }

  private buildApiPathFromFilePath(file: string) {
    // 'mini-blog/pages/api/create'
    // becomes
    // 'mini-blog/create'
    return file.split("/pages/api/").join("/");
  }

  private generateFileErrorHandling(error: NodeJS.ErrnoException | null) {
    if (error) console.error(error);
  }

  private fileContent(apiEndpointsContent: string) {
    return `// *********************************************************************
// This file is autogenerated with /cli/app-store-generate-files.ts
// Don't modify this file manually
// *********************************************************************
type ApiEndpoints = { [key: string]: unknown };\n
export const apiEndpoints: ApiEndpoints = {\n${apiEndpointsContent}};\n`;
  }
}
